# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20190123_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
