# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_todo_is_finished'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Todo',
            new_name='List',
        ),
    ]
