# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20190124_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='is_finished',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
